---
title: "Data Cleaning and Visualization of NTL Data"
author: "Josie Zenger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages, warning=FALSE, message=FALSE}
# Load packages
library(sf)
library(terra)
library(ggplot2)
library(tidyterra)
library(lubridate)
library(dplyr)
library(tmap)
library(raster)
library(rnaturalearth)
library(jsonlite)
library(dplyr)
library(tools)
library(utils)
library(plotly)
```


```{r Camp Fire Data}

# Load satellite data
camp_outputs <- list.files("~/Local/Dissertation/NTL_Wildfire_Recovery/CampFire_2_TIFFs", full.names = TRUE)

# Load in the camp fire csv
camp_csv <- read.csv("~/Local/Dissertation/NTl_Wildfire_Recovery/Camp_DailyMeanLuminosity.csv")

# Rasterize satellite data
camp_data <- lapply(camp_outputs, rast)

# Name the output rasters in satellite data based on the file names 
# Extract file names without extension and path
c.file_names <- tools::file_path_sans_ext(basename(camp_outputs))

# Name the list elements using extracted file names
names(camp_data) <- c.file_names


# Get rid of the Camp_ prefix
names(camp_data) <- gsub("Camp_", "", names(camp_data))

# Merge rasters with their corresponding metadata
c.combined_data <- lapply(names(camp_data), function(name) {
  list(
    raster = camp_data[[name]],
    metadata = camp_csv %>% filter(system.index == name)
  )
})

# Assign names to the combined list
names(c.combined_data) <- names(camp_data)

# Check merged structure
summary(c.combined_data)
plot(c.combined_data[[209]]$raster)

# print mean NTL after 2019-02-10 for the camp csv using Gap Filled THIS NEEDS TO CHANGE
mean_ntl_after <- mean(camp_csv$Gap_Filled_DNB_BRDF_Corrected_NTL[camp_csv$date > "2019-02-10"], na.rm = TRUE)


```

```{r Camp Fire stuff 1, warning=FALSE, message=FALSE}
# This section of code filters the Camp Fire data to only include rows where the Mandatory_Quality_Flag is less than or equal to 0.05, or where it is NA. It also aggregates the data by week and visualizes the NTL data across time. 

# Filter data based on Mandatory_Quality_Flag condition
f.camp_csv <- camp_csv %>% 
  filter(Mandatory_Quality_Flag <= 0.05 | is.na(Mandatory_Quality_Flag))

# Convert date columns to Date type
f.camp_csv$date <- as.Date(f.camp_csv$date)


# Aggregate by week
f.camp_weekly <- f.camp_csv %>%
  mutate(week = floor_date(date, "week")) %>%
  group_by(week) %>%
  summarize(mean_NTL = mean(Gap_Filled_DNB_BRDF_Corrected_NTL, na.rm = TRUE))


# Plot the trendlines from both datasets
ggplot(f.camp_weekly, aes(x = week, y = mean_NTL)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Weekly Average NTL in Camp Fire Data, Inclusive of Fire Weeks",
       x = "Date",
       y = "NTL Value") +
  theme_minimal() 


```

```{r Buffer area plotted, warning=FALSE, message=FALSE}

# This section of code filters the Buffer data to only include rows where the Mandatory_Quality_Flag is less than or equal to 0.05, or where it is NA. It also aggregates the data by week and visualizes the NTL data across time. 

# Load in the buffer csv
cbuff_csv <- read.csv("~/Local/Dissertation/NTL_Wildfire_Recovery/CBuff_DailyMeanLuminosity.csv")

# Filter data based on Mandatory_Quality_Flag condition
f.cbuff_csv <- cbuff_csv %>% 
  filter(Mandatory_Quality_Flag <= 0.05 | is.na(Mandatory_Quality_Flag))

# Convert date columns to Date type
f.cbuff_csv$date <- as.Date(f.cbuff_csv$date)

# Aggregate by week
f.cbuff_weekly <- f.cbuff_csv %>%
  mutate(week = floor_date(date, "week")) %>%
  group_by(week) %>%
  summarize(mean_NTL = mean(Gap_Filled_DNB_BRDF_Corrected_NTL, na.rm = TRUE))


# Plot the trendlines from both datasets
ggplot(f.cbuff_weekly, aes(x = week, y = mean_NTL)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Weekly Average NTL in Buffer Data, Inclusive of Fire Weeks",
       x = "Date",
       y = "NTL Value") +
  theme_minimal() 


```

```{r Combined Plots, warning=FALSE, message=FALSE}
# In this section of code, we combine the Camp Fire and Buffer datasets, add a source column to each, and plot the trendlines from both datasets.

# Add source column to both datasets
f.camp_csv$source <- "Camp Fire"
f.cbuff_csv$source <- "Buffer"

# Add source column to both datasets
f.cbuff_weekly$source <- "Buffer"
f.camp_weekly$source <- "Camp Fire"

# Combine the two dataframes (daily)
c.combined_csv <- bind_rows(f.cbuff_csv, f.camp_csv)
head(c.combined_csv)

# Combine the two dataframes (daily)
c.combined_weekly <- bind_rows(f.camp_weekly, f.cbuff_weekly)

# Plot the trendlines from both datasets with no filtering (daily)
ggplot(c.combined_csv, aes(x = date, y = Gap_Filled_DNB_BRDF_Corrected_NTL, color = source, group = source)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Smooth Trend Line of Daily NTL Data (Comparison)",
       x = "Date",
       y = "NTL Value") +
  scale_color_manual(values = c("blue4", "green4")) 

# Plot the datapoints from both datasets with no filtering (weekly). Include a smooth trend line. 
ggplot(c.combined_weekly, aes(x = week, y = mean_NTL, color = source, group = source)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Smooth Trend Line of Weekly Mean NTL Data: Camp Fire and Buffer Data",
       x = "Date",
       y = "NTL Value") +
  scale_color_manual(values = c("blue4", "green4")) 

# Create an filtered dataset that excludes the fire dates
f.combined_weekly <- c.combined_weekly %>%
  filter(week < as.Date("2018-11-04") | week > as.Date("2019-02-10"))

# Plot points for all data with smoothed lines only for non-excluded dates
ggplot(f.combined_weekly, aes(x = week, y = mean_NTL, color = source, group = source)) +
  geom_point() +
  geom_smooth(
    method = "loess", se = FALSE
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Broken Trend Line of NTL Data (Excluding Nov 4 – Feb 10)",
       x = "Date",
       y = "NTL Value") +
  scale_color_manual(values = c("blue4", "green4")) +
  scale_y_continuous(limits = c(0, 2.5)) 



```
```{r Filtered Combined Plots, warning=FALSE, message=FALSE}

# In this section of code, we filter the combined datasets to only include dates before and after the Camp Fire, and plot the trendlines from both datasets.


# On a week scale
f.camp_weeks_before <- c.combined_weekly %>%
  filter(week < as.Date("2018-11-04")) # Filter the data to only include dates before November 4th (the week of the fire)

# On a day scale
f.camp_days_before <- c.combined_csv %>%
  filter(date < as.Date("2018-11-08")) # Day of the fire

# Plot the data points from both datasets (on a day scale), include a smooth trend line
ggplot(f.camp_days_before, aes(x = date, y = Gap_Filled_DNB_BRDF_Corrected_NTL, color = source, group = source)) +
  geom_point() +
   geom_smooth(method = "loess", se = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Comparison of Mean NTL Values Before Camp Fire",
       x = "Date",
       y = "NTL Value") +
  scale_color_manual(values = c("blue4", "green4")) 

# Create a dataset that just includes the days after the fire
f.camp_days_after <- c.combined_csv %>%
  filter(date > as.Date("2019-02-10"))

# Plot the trendlines of the days after the fire (day scale)
ggplot(f.camp_days_after, aes(x = date, y = Gap_Filled_DNB_BRDF_Corrected_NTL, color = source, group = source)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Smooth Trend Line of NTL Data after Jan 07 (Comparison)",
       x = "Date",
       y = "NTL Value") +
  scale_color_manual(values = c("blue4", "green4"))


# Plot the weeks after the fire
f.camp_weeks_after <- c.combined_weekly %>%
  filter(week > as.Date("2019-02-10"))

# Plot the datapoints from both datasets (week scale), include a smooth trend line
ggplot(f.camp_weeks_after, aes(x = week, y = mean_NTL, color = source, group = source)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Smooth Trend Line of NTL Data after Jan 07 (Comparison)",
       x = "Date",
       y = "NTL Value") +
  scale_color_manual(values = c("blue4", "green4"))

```


```{r Difference in NTL, warning=FALSE, message=FALSE}
# In this section of code, we calculate the difference in NTL between the Camp Fire and Buffer datasets, adjust the dates for visual continuity, and plot the results with a dashed line indicating the break point.


ntl_diff_data <- c.combined_csv %>%
  select(date, source, Gap_Filled_DNB_BRDF_Corrected_NTL) %>%
  pivot_wider(names_from = source, values_from = Gap_Filled_DNB_BRDF_Corrected_NTL) %>%
  filter(!is.na(`Camp Fire`) & !is.na(Buffer)) %>%
  mutate(NTL_diff = `Camp Fire` - Buffer)

# Compute the date gap to adjust post-fire dates
end_before <- max(ntl_diff_data$date[ntl_diff_data$date < as.Date("2018-11-08")])
start_after <- min(ntl_diff_data$date[ntl_diff_data$date >= as.Date("2019-02-10")])
gap <- as.numeric(start_after - end_before) - 1  # to close the visual gap


# Adjust dates for visual continuity
f.before <- ntl_diff_data %>%
  filter(date < as.Date("2018-11-07")) %>% # dates before the fire
  mutate(date_adjusted = date)

f.after <- ntl_diff_data %>%
  filter(date >= as.Date("2019-02-10")) %>% # dates after the fire
  mutate(date_adjusted = date - gap)

f.all_adjusted <- bind_rows(f.before, f.after)

# Add dashed line at visual break point
break_adjusted <- max(f.before$date_adjusted)

# Plot
ggplot(f.all_adjusted, aes(x = date_adjusted, y = NTL_diff)) +
  geom_line(color = "lightgrey") +
  geom_vline(xintercept = as.numeric(break_adjusted), linetype = "dashed", color = "red") +
  annotate("text", x = break_adjusted + 2, y = max(f.all_adjusted$NTL_diff, na.rm = TRUE),
           label = "Camp Fire\nNov 8–Jan 7 excluded", color = "red", hjust = 0) +
  labs(
    title = "Difference in NTL (Camp - Buffer) Before and After Camp Fire",
    x = "Date (Adjusted)",
    y = "NTL Difference"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ntl_diff_f <- ntl_diff_data %>%
  filter(date < as.Date("2018-11-08"))

# Print the mean NTL_diff before the fire 
mean_ntl_diff <- mean(ntl_diff_f$NTL_diff, na.rm = TRUE)
mean_ntl_diff

```

```{r Calculations, warning=FALSE, message=FALSE}
# In this section of code, we do some simple calculations on the gap filled data to get a sense of basic differences between the buffer and treatment areas, and print the results.

# Print the mean NTL_diff after the fire
ntl_diff_a <- ntl_diff_data %>%
  filter(date >= as.Date("2019-02-10"))
mean_ntl_diff_after <- mean(ntl_diff_a$NTL_diff, na.rm = TRUE)
mean_ntl_diff_after

#Print the mean NTL from the time period after the fire 
mean_ntl_after <- mean(f.camp_days_after$Gap_Filled_DNB_BRDF_Corrected_NTL, na.rm = TRUE)
mean_ntl_after
# Print the mean NTL from the time period before the fire
mean_ntl_before <- mean(f.camp_days_before$Gap_Filled_DNB_BRDF_Corrected_NTL, na.rm = TRUE)

```



